### PR TITLE
1.3-beta5

### PR DESCRIPTION
**Pull request by slaxor505**
Added workaround for use case https://github.com/Olen/home-assistant-openplantbook/issues/20

### CODE REVIEW

**Comment by slaxor505** [comment]
Is there any reason you cannot merge it, @Olen ?

**Comment by Olen** [comment]
Only time

**Comment by Olen** [comment]
Let me know if you think I should release a "stable" version

**Comment by slaxor505** [comment]
Thank you. I just want to keep the number of users low at the moment as I
need to make some arrangements for increased traffic once it is released. I
will definitely let you know soon.

Slava

**Pull request merged**
